---
# msg
- name: Afficher un message
  debug:
    msg: message de tchube
# ping
- name: Example ping
  ansible.builtin.ping:
# update
- name: Update repositories cache and install foo
  apt:
#    name: foo
    update_cache: yes
  become: yes
